# Generated by Django 5.0 on 2024-01-08 11:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeedetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Firstname',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
